# Generated by Django 5.2 on 2025-10-17 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticuloCarro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CarroCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pagar", models.ImageField(null=True, upload_to="carrosCompra/")),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("pagado", models.BooleanField(default=False)),
                ("cerrado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="contratos/")),
                ("activo", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("empresa", "Contrato de Empresa"),
                            ("inmueble", "Contrato de Inmueble"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContratoFirmado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="contratos_firmados/")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("empresa", "Contrato de Empresa"),
                            ("inmueble", "Contrato de Inmueble"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estado", models.CharField(default="pendiente", max_length=20)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="empresas/")),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreE", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="eventos/")),
                ("capacidad", models.IntegerField(default=1)),
                ("fechahora", models.DateTimeField(default=datetime.datetime.now)),
                ("preciocover", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreI", models.CharField(max_length=255)),
                ("detalles", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="inmuebles/")),
                ("numagente", models.IntegerField(default=53957442)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arroyo_naranjo", "Arroyo Naranjo"),
                            ("boyeros", "Boyeros"),
                            ("cerro", "Cerro"),
                            ("cotorro", "Cotorro"),
                            ("diez_de_octubre", "Diez de Octubre"),
                            ("guanabacoa", "Guanabacoa"),
                            ("habana_del_este", "La Habana del Este"),
                            ("habana_vieja", "La Habana Vieja"),
                            ("la Lisa", "La Lisa"),
                            ("marianao", "Marianao"),
                            ("playa", "Playa"),
                            ("plaza", "Plaza de la Revolución"),
                            ("regla", "Regla"),
                            ("san_miguel_del_padron", "San Miguel del Padrón"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagen", "Imagen"), ("video", "Video")],
                        max_length=10,
                    ),
                ),
                ("archivo", models.FileField(upload_to="media/")),
                ("orden", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["orden", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreO", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="ofertas/")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("marketimg", "Marketing Digital"),
                            ("promocion", "Promoción y Publicidad"),
                            ("carteles", "Diseño de Carteles y Fotos"),
                            ("gestion", "Gestión de Compra y Venta Inmobiliaria"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreP", models.CharField(max_length=255)),
                ("detalles", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="productos/")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("turismo", "Turismo"),
                            ("comidas-bebidas", "Comidas y bebidas"),
                            ("articulo-hogar", "Articulos del hogar"),
                            ("belleza", "Belleza"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_personas", models.IntegerField(default=1)),
                ("num_confirm", models.IntegerField(default=0)),
                ("pagar", models.ImageField(null=True, upload_to="reservas/")),
                ("estado", models.BooleanField(default=False)),
                ("mensaje", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comentario", models.TextField(blank=True, max_length=1000)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
