# Generated by Django 4.1 on 2025-08-07 02:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="contratos/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contrato Oficial",
                "verbose_name_plural": "Contratos Oficiales",
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreE", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="eventos/")),
                ("capacidad", models.IntegerField(default=1)),
                ("fechahora", models.DateTimeField(default=datetime.datetime.now)),
                ("preciocover", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreI", models.CharField(max_length=255)),
                ("detalles", models.CharField(max_length=1000)),
                ("image", models.ImageField(upload_to="inmuebles/")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("arroyo_naranjo", "Arroyo Naranjo"),
                            ("boyeros", "Boyeros"),
                            ("cerro", "Cerro"),
                            ("cotorro", "Cotorro"),
                            ("diez_de_octubre", "Diez de Octubre"),
                            ("guanabacoa", "Guanabacoa"),
                            ("habana_del_este", "La Habana del Este"),
                            ("habana_vieja", "La Habana Vieja"),
                            ("la Lisa", "La Lisa"),
                            ("marianao", "Marianao"),
                            ("playa", "Playa"),
                            ("plaza", "Plaza de la Revolución"),
                            ("regla", "Regla"),
                            ("san_miguel_del_padron", "San Miguel del Padrón"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Oferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreO", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="ofertas/")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("marketimg", "Marketing Digital"),
                            ("promocion", "Promoción y Publicidad"),
                            ("carteles", "Diseño de Carteles y Fotos"),
                            ("gestion", "Gestión de Compra y Venta Inmobiliaria"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreP", models.CharField(max_length=255)),
                ("detalles", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="productos/")),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("turismo", "Turismo"),
                            ("comidas-bebidas", "Comidas y bebidas"),
                            ("articulo-hogar", "Articulos del hogar"),
                            ("belleza", "Belleza"),
                        ],
                        max_length=21,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Valoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comentario", models.TextField(blank=True, max_length=1000)),
                ("fecha", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="producto.evento",
                    ),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="producto.inmueble",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="producto.oferta",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones",
                        to="producto.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_personas", models.IntegerField(default=1)),
                ("num_confirm", models.IntegerField(default=0)),
                ("estado", models.BooleanField(default=False)),
                ("mensaje", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserva",
                        to="producto.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserva",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContratoFirmado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="contratos_firmados/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarroCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("enviado", models.BooleanField(default=False)),
                ("cerrado", models.BooleanField(default=False)),
                ("pagado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carritos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticuloCarro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
                (
                    "carrito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="producto.carrocompra",
                    ),
                ),
                (
                    "oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="producto.oferta",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="producto.producto",
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="producto.reserva",
                    ),
                ),
            ],
        ),
    ]
