# Generated by Django 4.1 on 2025-08-07 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valoracion",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="valoracion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valoraciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
