# Generated by Django 4.1 on 2025-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0002_alter_valoracion_fecha_alter_valoracion_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmueble",
            name="numagente",
            field=models.IntegerField(default=5353957442),
        ),
    ]
