# Generated by Django 4.1 on 2025-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0003_inmueble_numagente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="numagente",
            field=models.IntegerField(default=53957442),
        ),
    ]
