# Generated by Django 4.1 on 2025-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="img/user.png", upload_to="usuarios/"),
        ),
    ]
