# Generated by Django 4.1 on 2025-08-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(default="img/user.png", upload_to="img/"),
        ),
    ]
